steps:
  - name: 'mcr.microsoft.com/dotnet/sdk:8.0'
    id: 'Build'
    entrypoint: 'dotnet'
    args: ['publish', 'backend/backend/backend.csproj', '-c', 'Release', '-o', 'publish']

  - name: 'bash'
    id: 'Prepare Secret File'
    entrypoint: 'bash'
    args: ['-c', 'echo -n "$$DB_CONN_STRING_SECRET" > publish/connection_string.txt']
    secretEnv: ['DB_CONN_STRING_SECRET']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Copy Files'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'gcloud compute scp --recurse publish/ $$VM_INSTANCE_NAME_SECRET:/tmp/ --zone=$$VM_ZONE_SECRET'
    secretEnv: ['VM_INSTANCE_NAME_SECRET', 'VM_ZONE_SECRET']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Configure and Restart'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh $$VM_INSTANCE_NAME_SECRET --zone=$$VM_ZONE_SECRET --command='
          # Stop the service before making changes. "|| true" ignores errors if the service is not already running.
          sudo systemctl stop kestrel-backend.service || true

          # Set up the application directory
          sudo mkdir -p /var/www/backend
          # It is best practice to clean out old files before copying new ones.
          sudo rm -rf /var/www/backend/*
          sudo cp -r /tmp/publish/* /var/www/backend/
          sudo chown -R www-data:www-data /var/www/backend

          # Securely read the connection string from the file into a shell variable.
          CONN_STRING=$(sudo cat /var/www/backend/connection_string.txt)

          # Use a "here document" (cat <<EOF) to safely create the systemd service file.
          # This is the most reliable way to write multi-line text to a file in a script.
          sudo tee /etc/systemd/system/kestrel-backend.service > /dev/null <<EOF
        [Unit]
        Description=Backend .NET Web API
        [Service]
        WorkingDirectory=/var/www/backend
        ExecStart=/usr/share/dotnet/dotnet /var/www/backend/backend.dll
        Restart=always
        RestartSec=10
        User=www-data
        Environment=ASPNETCORE_ENVIRONMENT=Production
        Environment="ConnectionStrings__BasketballDBConnection=$${CONN_STRING}"
        [Install]
        WantedBy=multi-user.target
        EOF

          # For security, clean up the connection string file now that it has been loaded into the service definition.
          sudo rm /var/www/backend/connection_string.txt

          # Reload systemd to recognize the new/changed service file, then enable and start the service.
          sudo systemctl daemon-reload
          sudo systemctl enable kestrel-backend.service
          sudo systemctl start kestrel-backend.service

          # Restart the reverse proxy (like Nginx) if it exists.
          sudo systemctl restart nginx || true
        '
    secretEnv: ['VM_INSTANCE_NAME_SECRET', 'VM_ZONE_SECRET']
 # Seed DB
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Seed Database'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Exit immediately if a command exits with a non-zero status.
        set -e

        echo "--- Installing Database Tools ---"
        # The gcloud image is based on Debian. We need to install curl first.
        apt-get update -y && apt-get install -y curl

        # Use curl to download and start the Cloud SQL Auth Proxy.
        curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.10.1/cloud-sql-proxy.linux.amd64
        chmod +x cloud-sql-proxy
        # Start the proxy in the background to connect to the private IP of the SQL instance.
        ./cloud-sql-proxy $$DB_INSTANCE_CONN_NAME_SECRET &

        # Give the proxy a moment to initialize.
        sleep 10

        echo "--- Installing Microsoft SQL Server command-line tools (sqlcmd) ---"
        # Add the Microsoft package repository for Debian 11 (Bullseye), which the gcloud image is based on.
        curl https://packages.microsoft.com/keys/microsoft.asc | tee /etc/apt/trusted.gpg.d/microsoft.asc
        curl https://packages.microsoft.com/config/debian/11/prod.list | tee /etc/apt/sources.list.d/mssql-release.list
        
        # Install the tools. The ACCEPT_EULA flag is required.
        apt-get update -y
        ACCEPT_EULA=Y apt-get install -y mssql-tools

        echo "--- Seeding the database ---"
        # Run the SQL script. The tools are installed in /opt/mssql-tools/bin/
        /opt/mssql-tools/bin/sqlcmd -S tcp:127.0.0.1,1433 -U sqlserver -P "$$DB_ROOT_PASSWORD_SECRET" -d Basketball -i SQLQueryBB.sql
        echo "--- Database seeding complete ---"
    secretEnv: ['DB_INSTANCE_CONN_NAME_SECRET', 'DB_ROOT_PASSWORD_SECRET']
    waitFor: ['Configure and Restart'] # Run this step after the backend is deployed.
 # Frontend Job (runs in parallel with backend)
  - name: 'node:22'
    id: 'Build Frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend
        find src/app/environments -type f -name "environment.prod.ts" -exec sed -i "s|__API_URL_PLACEHOLDER__|http://$$LB_IP_SECRET|g" {} +
        npm install --legacy-peer-deps
        npm install -g @angular/cli
        ng build --configuration=production
    secretEnv: ['FRONTEND_BUCKET_NAME_SECRET', 'LB_IP_SECRET']
    waitFor: ['-']  
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy Frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil -m rsync -r -d frontend/dist/frontend/browser gs://$$FRONTEND_BUCKET_NAME_SECRET/
        
        gsutil -m setmeta -h "Cache-Control:public,max-age=31536000" gs://$$FRONTEND_BUCKET_NAME_SECRET/**/*.js
        gsutil -m setmeta -h "Cache-Control:public,max-age=31536000" gs://$$FRONTEND_BUCKET_NAME_SECRET/**/*.css
        gsutil -m setmeta -h "Cache-Control:no-cache" gs://$$FRONTEND_BUCKET_NAME_SECRET/index.html
    secretEnv: ['FRONTEND_BUCKET_NAME_SECRET']
    waitFor: ['Build Frontend']
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DB_CONNECTION_STRING/versions/latest
      env: 'DB_CONN_STRING_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/_VM_INSTANCE_NAME/versions/latest
      env: 'VM_INSTANCE_NAME_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/_VM_ZONE/versions/latest
      env: 'VM_ZONE_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/FRONTEND_BUCKET_NAME/versions/latest
      env: 'FRONTEND_BUCKET_NAME_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/LOAD_BALANCER_IP/versions/latest
      env: 'LB_IP_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/DB_INSTANCE_CONNECTION_NAME/versions/latest
      env: 'DB_INSTANCE_CONN_NAME_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/DB_ROOT_PASSWORD/versions/latest
      env: 'DB_ROOT_PASSWORD_SECRET'
options:
  logging: CLOUD_LOGGING_ONLY