steps:
  # Step 1: Build the .NET application
  - name: 'mcr.microsoft.com/dotnet/sdk:8.0'
    id: 'Build'
    entrypoint: 'dotnet'
    args: ['publish', 'backend/backend/backend.csproj', '-c', 'Release', '-o', 'publish']

  # Step 2: Copy the SQL script into the publish directory so it can be sent to the VM
  - name: 'bash'
    id: 'Prepare SQL Script'
    entrypoint: 'bash'
    args: ['-c', 'cp SQLQueryBB.sql publish/']
    waitFor: ['Build']

  # Step 3: Securely prepare files containing the secrets
  - name: 'bash'
    id: 'Prepare Secret Files'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo -n "$$DB_CONN_STRING_SECRET" > publish/connection_string.txt
        echo -n "$$DB_ROOT_PASSWORD_SECRET" > publish/db_password.txt
        echo -n "$$DB_IP_SECRET" > publish/db_ip.txt # New: Write the IP to a file
    secretEnv: ['DB_CONN_STRING_SECRET', 'DB_ROOT_PASSWORD_SECRET', 'DB_IP_SECRET'] # New: Add DB_IP_SECRET
    waitFor: ['Prepare SQL Script']

  # Step 4: A single step to copy files, configure the app, and seed the database from the VM
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy-Configure-and-Seed'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # First, copy the entire 'publish' directory to the VM.
        gcloud compute scp --recurse publish/ $$VM_INSTANCE_NAME_SECRET:/tmp/ --zone=$$VM_ZONE_SECRET

        # Now, SSH into the VM to perform all setup tasks.
        gcloud compute ssh $$VM_INSTANCE_NAME_SECRET --zone=$$VM_ZONE_SECRET --command='
          # ... (Part 1: .NET Service Configuration is the same) ...
          
          # --- Part 2: Seed the Database from the VM ---
          echo "--- Installing Database Tools on VM ---"
          # ... (Installation steps are the same) ...

          echo "--- Seeding the database from VM ---"
          # Securely read the password AND the IP from their files into variables.
          DB_PASS=$(sudo cat /var/www/backend/db_password.txt)
          DB_IP=$(sudo cat /var/www/backend/db_ip.txt) # New: Read the IP from its file

          # Use the new $$DB_IP variable in the command.
          /opt/mssql-tools/bin/sqlcmd -S tcp:$${DB_IP},1433 -U sqlserver -P "$${DB_PASS}" -d Basketball -i /var/www/backend/SQLQueryBB.sql

          # --- Part 3: Final Cleanup ---
          echo "--- Cleaning up temporary files ---"
          sudo rm /var/www/backend/db_password.txt
          sudo rm /var/www/backend/db_ip.txt # New: Clean up the IP file
          sudo rm -rf /tmp/publish
          echo "--- Deployment and Seeding Complete ---"
        '
    secretEnv: ['VM_INSTANCE_NAME_SECRET', 'VM_ZONE_SECRET']
    waitFor: ['Prepare Secret Files']
 # Frontend Job (runs in parallel with backend)
  - name: 'node:22'
    id: 'Build Frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend
        find src/app/environments -type f -name "environment.prod.ts" -exec sed -i "s|__API_URL_PLACEHOLDER__|http://$$LB_IP_SECRET|g" {} +
        npm install --legacy-peer-deps
        npm install -g @angular/cli
        ng build --configuration=production
    secretEnv: ['FRONTEND_BUCKET_NAME_SECRET', 'LB_IP_SECRET']
    waitFor: ['-']  
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy Frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil -m rsync -r -d frontend/dist/frontend/browser gs://$$FRONTEND_BUCKET_NAME_SECRET/
        
        gsutil -m setmeta -h "Cache-Control:public,max-age=31536000" gs://$$FRONTEND_BUCKET_NAME_SECRET/**/*.js
        gsutil -m setmeta -h "Cache-Control:public,max-age=31536000" gs://$$FRONTEND_BUCKET_NAME_SECRET/**/*.css
        gsutil -m setmeta -h "Cache-Control:no-cache" gs://$$FRONTEND_BUCKET_NAME_SECRET/index.html
    secretEnv: ['FRONTEND_BUCKET_NAME_SECRET']
    waitFor: ['Build Frontend']
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DB_CONNECTION_STRING/versions/latest
      env: 'DB_CONN_STRING_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/_VM_INSTANCE_NAME/versions/latest
      env: 'VM_INSTANCE_NAME_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/_VM_ZONE/versions/latest
      env: 'VM_ZONE_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/FRONTEND_BUCKET_NAME/versions/latest
      env: 'FRONTEND_BUCKET_NAME_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/LOAD_BALANCER_IP/versions/latest
      env: 'LB_IP_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/DB_ROOT_PASSWORD/versions/latest
      env: 'DB_ROOT_PASSWORD_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/DB_IP/versions/latest
      env: 'DB_IP_SECRET'
options:
  logging: CLOUD_LOGGING_ONLY