steps:
  - name: 'mcr.microsoft.com/dotnet/sdk:8.0'
    id: 'Build'
    entrypoint: 'dotnet'
    args: ['publish', 'backend/backend.csproj', '-c', 'Release', '-o', 'publish']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Copy Files'
    args:
      - 'compute'
      - 'scp'
      - '--recurse'
      - 'publish/'
      - '$$VM_INSTANCE_NAME_SECRET:/tmp/' 
      - '--zone=$$VM_ZONE_SECRET' 
    secretEnv: ['VM_INSTANCE_NAME_SECRET', 'VM_ZONE_SECRET']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Configure and Restart'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh $$VM_INSTANCE_NAME_SECRET --zone=$$VM_ZONE_SECRET --command='
          sudo systemctl stop kestrel-backend.service
          sudo mkdir -p /var/www/backend
          sudo cp -r /tmp/publish/* /var/www/backend/
          sudo chown -R www-data:www-data /var/www/backend
          echo "[Unit]
          Description=Backend .NET Web API
          [Service]
          WorkingDirectory=/var/www/backend
          ExecStart=/usr/bin/dotnet /var/www/backend/backend.dll
          Restart=always
          RestartSec=10
          User=www-data
          Environment=ASPNETCORE_ENVIRONMENT=Production
          Environment=\\\"ConnectionStrings__BasketballDBConnection=$$DB_CONN_STRING_SECRET\\\" # Changed from $ to $$ and escaped quotes
          [Install]
          WantedBy=multi-user.target" | sudo tee /etc/systemd/system/kestrel-backend.service
          sudo systemctl daemon-reload
          sudo systemctl enable kestrel-backend.service
          sudo systemctl start kestrel-backend.service
          sudo systemctl restart nginx
        '
    secretEnv: ['VM_INSTANCE_NAME_SECRET', 'VM_ZONE_SECRET', 'DB_CONN_STRING_SECRET']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DB_CONNECTION_STRING/versions/latest
      env: 'DB_CONN_STRING_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/VM_INSTANCE_NAME/versions/latest
      env: 'VM_INSTANCE_NAME_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/VM_ZONE/versions/latest
      env: 'VM_ZONE_SECRET'

options:
  logging: CLOUD_LOGGING_ONLY